version: '1.0'

services:
  cmsapi:
    container_name: car-service-shop-manage
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8083:80

networks:
  default:
      name: srvnecmettin