namespace aracyonetim.database
{
    public class Seeds
    {
        public static string[] Markalar =
        {
            "ALFA ROMEO",
            "AUDI",
            "BENTLEY",
            "BMW",
            "CHERY",
            "CHEVROLET",
            "CHRYSLER",
            "CITROEN",
            "DACIA",
            "DAIHATSU",
            "DFM",
            "DODGE",
            "FERRARI",
            "FIAT",
            "FORD",
            "GEELY",
            "GREAT WALL",
            "HONDA",
            "HYUNDAI",
            "IKCO",
            "JAGUAR",
            "JEEP",
            "KARSAN",
            "KIA",
            "LADA",
            "LAMBORGINI",
            "LANCIA",
            "LAND ROVER",
            "MAHINDRA",
            "MASERATI",
            "MAZDA",
            "MERCEDES – BENZ",
            "MINI",
            "MITSUBISHI",
            "NISSAN",
            "OPEL",
            "OTOKAR",
            "PEUGEOT",
            "PORSCHE",
            "PROTON",
            "RENAULT",
            "SAAB",
            "SEAT",
            "SKODA",
            "SMART",
            "SSANGYONG",
            "SUBARU",
            "SUZUKI",
            "TATA",
            "TOYOTA",
            "VOLKSWAGEN",
            "VOLVO"
        };

        public static string[] IlIlce =
        {
            "Adana-Seyhan",
            "Adana-Ceyhan",
            "Adana-Feke",
            "Adana-Karaisalı",
            "Adana-Karataş",
            "Adana-Kozan",
            "Adana-Pozantı",
            "Adana-Saimbeyli",
            "Adana-Tufanbeyli",
            "Adana-Yumurtalık",
            "Adana-Yüreğir",
            "Adana-Aladağ",
            "Adana-İmamoğlu",
            "Adana-Sarıçam",
            "Adana-Çukurova",
            "Adıyaman-Adıyaman Merkez",
            "Adıyaman-Besni",
            "Adıyaman-Çelikhan",
            "Adıyaman-Gerger",
            "Adıyaman-Gölbaşı / Adıyaman",
            "Adıyaman-Kahta",
            "Adıyaman-Samsat",
            "Adıyaman-Sincik",
            "Adıyaman-Tut",
            "Afyonkarahisar-Afyonkarahisar Merkez",
            "Afyonkarahisar-Bolvadin",
            "Afyonkarahisar-Çay",
            "Afyonkarahisar-Dazkırı",
            "Afyonkarahisar-Dinar",
            "Afyonkarahisar-Emirdağ",
            "Afyonkarahisar-İhsaniye",
            "Afyonkarahisar-Sandıklı",
            "Afyonkarahisar-Sinanpaşa",
            "Afyonkarahisar-Sultandağı",
            "Afyonkarahisar-Şuhut",
            "Afyonkarahisar-Başmakçı",
            "Afyonkarahisar-Bayat / Afyonkarahisar",
            "Afyonkarahisar-İscehisar",
            "Afyonkarahisar-Çobanlar",
            "Afyonkarahisar-Evciler",
            "Afyonkarahisar-Hocalar",
            "Afyonkarahisar-Kızılören",
            "Ağrı-Ağrı Merkez",
            "Ağrı-Diyadin",
            "Ağrı-Doğubayazıt",
            "Ağrı-Eleşkirt",
            "Ağrı-Hamur",
            "Ağrı-Patnos",
            "Ağrı-Taşlıçay",
            "Ağrı-Tutak",
            "Amasya-Amasya Merkez",
            "Amasya-Göynücek",
            "Amasya-Gümüşhacıköy",
            "Amasya-Merzifon",
            "Amasya-Suluova",
            "Amasya-Taşova",
            "Amasya-Hamamözü",
            "Ankara-Altındağ",
            "Ankara-Ayaş",
            "Ankara-Bala",
            "Ankara-Beypazarı",
            "Ankara-Çamlıdere",
            "Ankara-Çankaya",
            "Ankara-Çubuk",
            "Ankara-Elmadağ",
            "Ankara-Güdül",
            "Ankara-Haymana",
            "Ankara-Kalecik",
            "Ankara-Kızılcahamam",
            "Ankara-Nallıhan",
            "Ankara-Polatlı",
            "Ankara-Şereflikoçhisar",
            "Ankara-Yenimahalle",
            "Ankara-Gölbaşı / Ankara",
            "Ankara-Keçiören",
            "Ankara-Mamak",
            "Ankara-Sincan",
            "Ankara-Kazan",
            "Ankara-Akyurt",
            "Ankara-Etimesgut",
            "Ankara-Evren",
            "Ankara-Pursaklar",
            "Antalya-Akseki",
            "Antalya-Alanya",
            "Antalya-Antalya Merkez",
            "Antalya-Elmalı",
            "Antalya-Finike",
            "Antalya-Gazipaşa",
            "Antalya-Gündoğmuş",
            "Antalya-Kaş",
            "Antalya-Korkuteli",
            "Antalya-Kumluca",
            "Antalya-Manavgat",
            "Antalya-Serik",
            "Antalya-Demre",
            "Antalya-İbradı",
            "Antalya-Kemer / Antalya",
            "Antalya-Aksu / Antalya",
            "Antalya-Döşemealtı",
            "Antalya-Kepez",
            "Antalya-Konyaaltı",
            "Antalya-Muratpaşa",
            "Artvin-Ardanuç",
            "Artvin-Arhavi",
            "Artvin-Artvin Merkez",
            "Artvin-Borçka",
            "Artvin-Hopa",
            "Artvin-Şavşat",
            "Artvin-Yusufeli",
            "Artvin-Murgul",
            "Artvin-Kemalpaşa / Artvin",
            "Aydın-Aydın Merkez",
            "Aydın-Bozdoğan",
            "Aydın-Çine",
            "Aydın-Germencik",
            "Aydın-Karacasu",
            "Aydın-Koçarlı",
            "Aydın-Kuşadası",
            "Aydın-Kuyucak",
            "Aydın-Nazilli",
            "Aydın-Söke",
            "Aydın-Sultanhisar",
            "Aydın-Yenipazar / Aydın",
            "Aydın-Buharkent",
            "Aydın-İncirliova",
            "Aydın-Karpuzlu",
            "Aydın-Köşk",
            "Aydın-Didim",
            "Aydın-Efeler",
            "Balıkesir-Ayvalık",
            "Balıkesir-Balıkesir Merkez",
            "Balıkesir-Balya",
            "Balıkesir-Bandırma",
            "Balıkesir-Bigadiç",
            "Balıkesir-Burhaniye",
            "Balıkesir-Dursunbey",
            "Balıkesir-Edremit / Balıkesir",
            "Balıkesir-Erdek",
            "Balıkesir-Gönen / Balıkesir",
            "Balıkesir-Havran",
            "Balıkesir-İvrindi",
            "Balıkesir-Kepsut",
            "Balıkesir-Manyas",
            "Balıkesir-Savaştepe",
            "Balıkesir-Sındırgı",
            "Balıkesir-Susurluk",
            "Balıkesir-Marmara",
            "Balıkesir-Gömeç",
            "Balıkesir-Altıeylül",
            "Balıkesir-Karesi",
            "Bilecik-Bilecik Merkez",
            "Bilecik-Bozüyük",
            "Bilecik-Gölpazarı",
            "Bilecik-Osmaneli",
            "Bilecik-Pazaryeri",
            "Bilecik-Söğüt",
            "Bilecik-Yenipazar / Bilecik",
            "Bilecik-İnhisar",
            "Bingöl-Bingöl Merkez",
            "Bingöl-Genç",
            "Bingöl-Karlıova",
            "Bingöl-Kiğı",
            "Bingöl-Solhan",
            "Bingöl-Adaklı",
            "Bingöl-Yayladere",
            "Bingöl-Yedisu",
            "Bitlis-Adilcevaz",
            "Bitlis-Ahlat",
            "Bitlis-Bitlis Merkez",
            "Bitlis-Hizan",
            "Bitlis-Mutki",
            "Bitlis-Tatvan",
            "Bitlis-Güroymak",
            "Bolu-Bolu Merkez",
            "Bolu-Gerede",
            "Bolu-Göynük",
            "Bolu-Kıbrıscık",
            "Bolu-Mengen",
            "Bolu-Mudurnu",
            "Bolu-Seben",
            "Bolu-Dörtdivan",
            "Bolu-Yeniçağa",
            "Burdur-Ağlasun",
            "Burdur-Bucak",
            "Burdur-Burdur Merkez",
            "Burdur-Gölhisar",
            "Burdur-Tefenni",
            "Burdur-Yeşilova",
            "Burdur-Karamanlı",
            "Burdur-Kemer / Burdur",
            "Burdur-Altınyayla / Burdur",
            "Burdur-Çavdır",
            "Burdur-Çeltikçi",
            "Bursa-Gemlik",
            "Bursa-İnegöl",
            "Bursa-İznik",
            "Bursa-Karacabey",
            "Bursa-Keles",
            "Bursa-Mudanya",
            "Bursa-Mustafakemalpaşa",
            "Bursa-Orhaneli",
            "Bursa-Orhangazi",
            "Bursa-Yenişehir / Bursa",
            "Bursa-Büyükorhan",
            "Bursa-Harmancık",
            "Bursa-Nilüfer",
            "Bursa-Osmangazi",
            "Bursa-Yıldırım",
            "Bursa-Gürsu",
            "Bursa-Kestel",
            "Çanakkale-Ayvacık / Çanakkale",
            "Çanakkale-Bayramiç",
            "Çanakkale-Biga",
            "Çanakkale-Bozcaada",
            "Çanakkale-Çan",
            "Çanakkale-Çanakkale Merkez",
            "Çanakkale-Eceabat",
            "Çanakkale-Ezine",
            "Çanakkale-Gelibolu",
            "Çanakkale-Gökçeada",
            "Çanakkale-Lapseki",
            "Çanakkale-Yenice / Çanakkale",
            "Çankırı-Çankırı Merkez",
            "Çankırı-Çerkeş",
            "Çankırı-Eldivan",
            "Çankırı-Ilgaz",
            "Çankırı-Kurşunlu",
            "Çankırı-Orta",
            "Çankırı-Şabanözü",
            "Çankırı-Yapraklı",
            "Çankırı-Atkaracalar",
            "Çankırı-Kızılırmak",
            "Çankırı-Bayramören",
            "Çankırı-Korgun",
            "Çorum-Alaca",
            "Çorum-Bayat / Çorum",
            "Çorum-Çorum Merkez",
            "Çorum-İskilip",
            "Çorum-Kargı",
            "Çorum-Mecitözü",
            "Çorum-Ortaköy / Çorum",
            "Çorum-Osmancık",
            "Çorum-Sungurlu",
            "Çorum-Boğazkale",
            "Çorum-Uğurludağ",
            "Çorum-Dodurga",
            "Çorum-Laçin",
            "Çorum-Oğuzlar",
            "Denizli-Acıpayam",
            "Denizli-Buldan",
            "Denizli-Çal",
            "Denizli-Çameli",
            "Denizli-Çardak",
            "Denizli-Çivril",
            "Denizli-Denizli Merkez",
            "Denizli-Güney",
            "Denizli-Kale / Denizli",
            "Denizli-Sarayköy",
            "Denizli-Tavas",
            "Denizli-Babadağ",
            "Denizli-Bekilli",
            "Denizli-Honaz",
            "Denizli-Serinhisar",
            "Denizli-Pamukkale",
            "Denizli-Baklan",
            "Denizli-Beyağaç",
            "Denizli-Bozkurt / Denizli",
            "Denizli-Merkezefendi",
            "Diyarbakır-Bismil",
            "Diyarbakır-Çermik",
            "Diyarbakır-Çınar",
            "Diyarbakır-Çüngüş",
            "Diyarbakır-Dicle",
            "Diyarbakır-Diyarbakır Merkez",
            "Diyarbakır-Ergani",
            "Diyarbakır-Hani",
            "Diyarbakır-Hazro",
            "Diyarbakır-Kulp",
            "Diyarbakır-Lice",
            "Diyarbakır-Silvan",
            "Diyarbakır-Eğil",
            "Diyarbakır-Kocaköy",
            "Diyarbakır-Bağlar",
            "Diyarbakır-Kayapınar",
            "Diyarbakır-Sur",
            "Diyarbakır-Yenişehir / Diyarbakır",
            "Edirne-Edirne Merkez",
            "Edirne-Enez",
            "Edirne-Havsa",
            "Edirne-İpsala",
            "Edirne-Keşan",
            "Edirne-Lalapaşa",
            "Edirne-Meriç",
            "Edirne-Uzunköprü",
            "Edirne-Süloğlu",
            "Elazığ-Ağın",
            "Elazığ-Baskil",
            "Elazığ-Elazığ Merkez",
            "Elazığ-Karakoçan",
            "Elazığ-Keban",
            "Elazığ-Maden",
            "Elazığ-Palu",
            "Elazığ-Sivrice",
            "Elazığ-Arıcak",
            "Elazığ-Kovancılar",
            "Elazığ-Alacakaya",
            "Erzincan-Çayırlı",
            "Erzincan-Erzincan Merkez",
            "Erzincan-İliç",
            "Erzincan-Kemah",
            "Erzincan-Kemaliye",
            "Erzincan-Refahiye",
            "Erzincan-Tercan",
            "Erzincan-Üzümlü",
            "Erzincan-Otlukbeli",
            "Erzurum-Aşkale",
            "Erzurum-Çat",
            "Erzurum-Erzurum Merkez",
            "Erzurum-Hınıs",
            "Erzurum-Horasan",
            "Erzurum-İspir",
            "Erzurum-Karayazı",
            "Erzurum-Narman",
            "Erzurum-Oltu",
            "Erzurum-Olur",
            "Erzurum-Pasinler",
            "Erzurum-Şenkaya",
            "Erzurum-Tekman",
            "Erzurum-Tortum",
            "Erzurum-Karaçoban",
            "Erzurum-Uzundere",
            "Erzurum-Pazaryolu",
            "Erzurum-Aziziye",
            "Erzurum-Köprüköy",
            "Erzurum-Palandöken",
            "Erzurum-Yakutiye",
            "Eskişehir-Çifteler",
            "Eskişehir-Eskişehir Merkez",
            "Eskişehir-Mahmudiye",
            "Eskişehir-Mihalıççık",
            "Eskişehir-Sarıcakaya",
            "Eskişehir-Seyitgazi",
            "Eskişehir-Sivrihisar",
            "Eskişehir-Alpu",
            "Eskişehir-Beylikova",
            "Eskişehir-İnönü",
            "Eskişehir-Günyüzü",
            "Eskişehir-Han",
            "Eskişehir-Mihalgazi",
            "Eskişehir-Odunpazarı",
            "Eskişehir-Tepebaşı",
            "Gaziantep-Araban",
            "Gaziantep-İslahiye",
            "Gaziantep-Nizip",
            "Gaziantep-Oğuzeli",
            "Gaziantep-Yavuzeli",
            "Gaziantep-Şahinbey",
            "Gaziantep-Şehitkamil",
            "Gaziantep-Karkamış",
            "Gaziantep-Nurdağı",
            "Giresun-Alucra",
            "Giresun-Bulancak",
            "Giresun-Dereli",
            "Giresun-Espiye",
            "Giresun-Eynesil",
            "Giresun-Giresun Merkez",
            "Giresun-Görele",
            "Giresun-Keşap",
            "Giresun-Şebinkarahisar",
            "Giresun-Tirebolu",
            "Giresun-Piraziz",
            "Giresun-Yağlıdere",
            "Giresun-Çamoluk",
            "Giresun-Çanakçı",
            "Giresun-Doğankent",
            "Giresun-Güce",
            "Gümüşhane-Gümüşhane Merkez",
            "Gümüşhane-Kelkit",
            "Gümüşhane-Şiran",
            "Gümüşhane-Torul",
            "Gümüşhane-Köse",
            "Gümüşhane-Kürtün",
            "Hakkari-Çukurca",
            "Hakkari-Hakkari Merkez",
            "Hakkari-Şemdinli",
            "Hakkari-Yüksekova",
            "Hatay-Altınözü",
            "Hatay-Dörtyol",
            "Hatay-Hassa",
            "Hatay-Hatay Merkez",
            "Hatay-İskenderun",
            "Hatay-Kırıkhan",
            "Hatay-Reyhanlı",
            "Hatay-Samandağ",
            "Hatay-Yayladağı",
            "Hatay-Erzin",
            "Hatay-Belen",
            "Hatay-Kumlu",
            "Hatay-Antakya",
            "Hatay-Arsuz",
            "Hatay-Defne",
            "Hatay-Payas",
            "Isparta-Atabey",
            "Isparta-Eğirdir",
            "Isparta-Gelendost",
            "Isparta-Isparta Merkez",
            "Isparta-Keçiborlu",
            "Isparta-Senirkent",
            "Isparta-Sütçüler",
            "Isparta-Şarkikaraağaç",
            "Isparta-Uluborlu",
            "Isparta-Yalvaç",
            "Isparta-Aksu / Isparta",
            "Isparta-Gönen / Isparta",
            "Isparta-Yenişarbademli",
            "Mersin-Anamur",
            "Mersin-Erdemli",
            "Mersin-Gülnar",
            "Mersin-Mersin Merkez",
            "Mersin-Mut",
            "Mersin-Silifke",
            "Mersin-Tarsus",
            "Mersin-Aydıncık / Mersin",
            "Mersin-Bozyazı",
            "Mersin-Çamlıyayla",
            "Mersin-Akdeniz",
            "Mersin-Mezitli",
            "Mersin-Toroslar",
            "Mersin-Yenişehir / Mersin",
            "İstanbul-Adalar",
            "İstanbul-Bakırköy",
            "İstanbul-Beşiktaş",
            "İstanbul-Beykoz",
            "İstanbul-Beyoğlu",
            "İstanbul-Çatalca",
            "İstanbul-Eminönü",
            "İstanbul-Eyüp",
            "İstanbul-Fatih",
            "İstanbul-Gaziosmanpaşa",
            "İstanbul-Kadıköy",
            "İstanbul-Kartal",
            "İstanbul-Sarıyer",
            "İstanbul-Silivri",
            "İstanbul-Şile",
            "İstanbul-Şişli",
            "İstanbul-Üsküdar",
            "İstanbul-Zeytinburnu",
            "İstanbul-Büyükçekmece",
            "İstanbul-Kağıthane",
            "İstanbul-Küçükçekmece",
            "İstanbul-Pendik",
            "İstanbul-Ümraniye",
            "İstanbul-Bayrampaşa",
            "İstanbul-Avcılar",
            "İstanbul-Bağcılar",
            "İstanbul-Bahçelievler",
            "İstanbul-Güngören",
            "İstanbul-Maltepe",
            "İstanbul-Sultanbeyli",
            "İstanbul-Tuzla",
            "İstanbul-Esenler",
            "İstanbul-Arnavutköy",
            "İstanbul-Ataşehir",
            "İstanbul-Başakşehir",
            "İstanbul-Beylikdüzü",
            "İstanbul-Çekmeköy",
            "İstanbul-Esenyurt",
            "İstanbul-Sancaktepe",
            "İstanbul-Sultangazi",
            "İzmir-Aliağa",
            "İzmir-Bayındır",
            "İzmir-Bergama",
            "İzmir-Bornova",
            "İzmir-Çeşme",
            "İzmir-Dikili",
            "İzmir-Foça",
            "İzmir-Karaburun",
            "İzmir-Karşıyaka",
            "İzmir-Kemalpaşa / İzmir",
            "İzmir-Kınık",
            "İzmir-Kiraz",
            "İzmir-Menemen",
            "İzmir-Ödemiş",
            "İzmir-Seferihisar",
            "İzmir-Selçuk",
            "İzmir-Tire",
            "İzmir-Torbalı",
            "İzmir-Urla",
            "İzmir-Beydağ",
            "İzmir-Buca",
            "İzmir-Konak",
            "İzmir-Menderes",
            "İzmir-Balçova",
            "İzmir-Çiğli",
            "İzmir-Gaziemir",
            "İzmir-Narlıdere",
            "İzmir-Güzelbahçe",
            "İzmir-Bayraklı",
            "İzmir-Karabağlar",
            "Kars-Arpaçay",
            "Kars-Digor",
            "Kars-Kağızman",
            "Kars-Kars Merkez",
            "Kars-Sarıkamış",
            "Kars-Selim",
            "Kars-Susuz",
            "Kars-Akyaka",
            "Kastamonu-Abana",
            "Kastamonu-Araç",
            "Kastamonu-Azdavay",
            "Kastamonu-Bozkurt / Kastamonu",
            "Kastamonu-Cide",
            "Kastamonu-Çatalzeytin",
            "Kastamonu-Daday",
            "Kastamonu-Devrekani",
            "Kastamonu-İnebolu",
            "Kastamonu-Kastamonu Merkez",
            "Kastamonu-Küre",
            "Kastamonu-Taşköprü",
            "Kastamonu-Tosya",
            "Kastamonu-İhsangazi",
            "Kastamonu-Pınarbaşı / Kastamonu",
            "Kastamonu-Şenpazar",
            "Kastamonu-Ağlı",
            "Kastamonu-Doğanyurt",
            "Kastamonu-Hanönü",
            "Kastamonu-Seydiler",
            "Kayseri-Bünyan",
            "Kayseri-Develi",
            "Kayseri-Felahiye",
            "Kayseri-İncesu",
            "Kayseri-Pınarbaşı / Kayseri",
            "Kayseri-Sarıoğlan",
            "Kayseri-Sarız",
            "Kayseri-Tomarza",
            "Kayseri-Yahyalı",
            "Kayseri-Yeşilhisar",
            "Kayseri-Akkışla",
            "Kayseri-Talas",
            "Kayseri-Kocasinan",
            "Kayseri-Melikgazi",
            "Kayseri-Hacılar",
            "Kayseri-Özvatan",
            "Kırklareli-Babaeski",
            "Kırklareli-Demirköy",
            "Kırklareli-Kırklareli Merkez",
            "Kırklareli-Kofçaz",
            "Kırklareli-Lüleburgaz",
            "Kırklareli-Pehlivanköy",
            "Kırklareli-Pınarhisar",
            "Kırklareli-Vize",
            "Kırşehir-Çiçekdağı",
            "Kırşehir-Kaman",
            "Kırşehir-Kırşehir Merkez",
            "Kırşehir-Mucur",
            "Kırşehir-Akpınar",
            "Kırşehir-Akçakent",
            "Kırşehir-Boztepe",
            "Kocaeli-Gebze",
            "Kocaeli-Gölcük",
            "Kocaeli-Kandıra",
            "Kocaeli-Karamürsel",
            "Kocaeli-Kocaeli Merkez",
            "Kocaeli-Körfez",
            "Kocaeli-Derince",
            "Kocaeli-Başiskele",
            "Kocaeli-Çayırova",
            "Kocaeli-Darıca",
            "Kocaeli-Dilovası",
            "Kocaeli-İzmit",
            "Kocaeli-Kartepe",
            "Konya-Akşehir",
            "Konya-Beyşehir",
            "Konya-Bozkır",
            "Konya-Cihanbeyli",
            "Konya-Çumra",
            "Konya-Doğanhisar",
            "Konya-Ereğli / Konya",
            "Konya-Hadim",
            "Konya-Ilgın",
            "Konya-Kadınhanı",
            "Konya-Karapınar",
            "Konya-Kulu",
            "Konya-Sarayönü",
            "Konya-Seydişehir",
            "Konya-Yunak",
            "Konya-Akören",
            "Konya-Altınekin",
            "Konya-Derebucak",
            "Konya-Hüyük",
            "Konya-Karatay",
            "Konya-Meram",
            "Konya-Selçuklu",
            "Konya-Taşkent",
            "Konya-Ahırlı",
            "Konya-Çeltik",
            "Konya-Derbent",
            "Konya-Emirgazi",
            "Konya-Güneysınır",
            "Konya-Halkapınar",
            "Konya-Tuzlukçu",
            "Konya-Yalıhüyük",
            "Kütahya-Altıntaş",
            "Kütahya-Domaniç",
            "Kütahya-Emet",
            "Kütahya-Gediz",
            "Kütahya-Kütahya Merkez",
            "Kütahya-Simav",
            "Kütahya-Tavşanlı",
            "Kütahya-Aslanapa",
            "Kütahya-Dumlupınar",
            "Kütahya-Hisarcık",
            "Kütahya-Şaphane",
            "Kütahya-Çavdarhisar",
            "Kütahya-Pazarlar",
            "Malatya-Akçadağ",
            "Malatya-Arapgir",
            "Malatya-Arguvan",
            "Malatya-Darende",
            "Malatya-Doğanşehir",
            "Malatya-Hekimhan",
            "Malatya-Malatya Merkez",
            "Malatya-Pütürge",
            "Malatya-Yeşilyurt / Malatya",
            "Malatya-Battalgazi",
            "Malatya-Doğanyol",
            "Malatya-Kale / Malatya",
            "Malatya-Kuluncak",
            "Malatya-Yazıhan",
            "Manisa-Akhisar",
            "Manisa-Alaşehir",
            "Manisa-Demirci",
            "Manisa-Gördes",
            "Manisa-Kırkağaç",
            "Manisa-Kula",
            "Manisa-Manisa Merkez",
            "Manisa-Salihli",
            "Manisa-Sarıgöl",
            "Manisa-Saruhanlı",
            "Manisa-Selendi",
            "Manisa-Soma",
            "Manisa-Turgutlu",
            "Manisa-Ahmetli",
            "Manisa-Gölmarmara",
            "Manisa-Köprübaşı / Manisa",
            "Manisa-Şehzadeler",
            "Manisa-Yunusemre",
            "Kahramanmaraş-Afşin",
            "Kahramanmaraş-Andırın",
            "Kahramanmaraş-Elbistan",
            "Kahramanmaraş-Göksun",
            "Kahramanmaraş-Kahramanmaraş Merkez",
            "Kahramanmaraş-Pazarcık",
            "Kahramanmaraş-Türkoğlu",
            "Kahramanmaraş-Çağlayancerit",
            "Kahramanmaraş-Ekinözü",
            "Kahramanmaraş-Nurhak",
            "Kahramanmaraş-Dulkadiroğlu",
            "Kahramanmaraş-Onikişubat",
            "Mardin-Derik",
            "Mardin-Kızıltepe",
            "Mardin-Mardin Merkez",
            "Mardin-Mazıdağı",
            "Mardin-Midyat",
            "Mardin-Nusaybin",
            "Mardin-Ömerli",
            "Mardin-Savur",
            "Mardin-Dargeçit",
            "Mardin-Yeşilli",
            "Mardin-Artuklu",
            "Muğla-Bodrum",
            "Muğla-Datça",
            "Muğla-Fethiye",
            "Muğla-Köyceğiz",
            "Muğla-Marmaris",
            "Muğla-Milas",
            "Muğla-Muğla Merkez",
            "Muğla-Ula",
            "Muğla-Yatağan",
            "Muğla-Dalaman",
            "Muğla-Ortaca",
            "Muğla-Kavaklıdere",
            "Muğla-Menteşe",
            "Muğla-Seydikemer",
            "Muş-Bulanık",
            "Muş-Malazgirt",
            "Muş-Muş Merkez",
            "Muş-Varto",
            "Muş-Hasköy",
            "Muş-Korkut",
            "Nevşehir-Avanos",
            "Nevşehir-Derinkuyu",
            "Nevşehir-Gülşehir",
            "Nevşehir-Hacıbektaş",
            "Nevşehir-Kozaklı",
            "Nevşehir-Nevşehir Merkez",
            "Nevşehir-Ürgüp",
            "Nevşehir-Acıgöl",
            "Niğde-Bor",
            "Niğde-Çamardı",
            "Niğde-Niğde Merkez",
            "Niğde-Ulukışla",
            "Niğde-Altunhisar",
            "Niğde-Çiftlik",
            "Ordu-Akkuş",
            "Ordu-Aybastı",
            "Ordu-Fatsa",
            "Ordu-Gölköy",
            "Ordu-Korgan",
            "Ordu-Kumru",
            "Ordu-Mesudiye",
            "Ordu-Ordu Merkez",
            "Ordu-Perşembe",
            "Ordu-Ulubey / Ordu",
            "Ordu-Ünye",
            "Ordu-Gülyalı",
            "Ordu-Gürgentepe",
            "Ordu-Çamaş",
            "Ordu-Çatalpınar",
            "Ordu-Çaybaşı",
            "Ordu-İkizce",
            "Ordu-Kabadüz",
            "Ordu-Kabataş",
            "Ordu-Altınordu",
            "Rize-Ardeşen",
            "Rize-Çamlıhemşin",
            "Rize-Çayeli",
            "Rize-Fındıklı",
            "Rize-İkizdere",
            "Rize-Kalkandere",
            "Rize-Pazar / Rize",
            "Rize-Rize Merkez",
            "Rize-Güneysu",
            "Rize-Derepazarı",
            "Rize-Hemşin",
            "Rize-İyidere",
            "Sakarya-Akyazı",
            "Sakarya-Geyve",
            "Sakarya-Hendek",
            "Sakarya-Karasu",
            "Sakarya-Kaynarca",
            "Sakarya-Sakarya Merkez",
            "Sakarya-Sapanca",
            "Sakarya-Kocaali",
            "Sakarya-Pamukova",
            "Sakarya-Taraklı",
            "Sakarya-Ferizli",
            "Sakarya-Karapürçek",
            "Sakarya-Söğütlü",
            "Sakarya-Adapazarı",
            "Sakarya-Arifiye",
            "Sakarya-Erenler",
            "Sakarya-Serdivan",
            "Samsun-Alaçam",
            "Samsun-Bafra",
            "Samsun-Çarşamba",
            "Samsun-Havza",
            "Samsun-Kavak",
            "Samsun-Ladik",
            "Samsun-Samsun Merkez",
            "Samsun-Terme",
            "Samsun-Vezirköprü",
            "Samsun-Asarcık",
            "Samsun-19 Mayıs",
            "Samsun-Salıpazarı",
            "Samsun-Tekkeköy",
            "Samsun-Ayvacık / Samsun",
            "Samsun-Yakakent",
            "Samsun-Atakum",
            "Samsun-Canik",
            "Samsun-İlkadım",
            "Siirt-Baykan",
            "Siirt-Eruh",
            "Siirt-Kurtalan",
            "Siirt-Pervari",
            "Siirt-Siirt Merkez",
            "Siirt-Şirvan",
            "Siirt-Tillo",
            "Sinop-Ayancık",
            "Sinop-Boyabat",
            "Sinop-Durağan",
            "Sinop-Erfelek",
            "Sinop-Gerze",
            "Sinop-Sinop Merkez",
            "Sinop-Türkeli",
            "Sinop-Dikmen",
            "Sinop-Saraydüzü",
            "Sivas-Divriği",
            "Sivas-Gemerek",
            "Sivas-Gürün",
            "Sivas-Hafik",
            "Sivas-İmranlı",
            "Sivas-Kangal",
            "Sivas-Koyulhisar",
            "Sivas-Sivas Merkez",
            "Sivas-Suşehri",
            "Sivas-Şarkışla",
            "Sivas-Yıldızeli",
            "Sivas-Zara",
            "Sivas-Akıncılar",
            "Sivas-Altınyayla / Sivas",
            "Sivas-Doğanşar",
            "Sivas-Gölova",
            "Sivas-Ulaş",
            "Tekirdağ-Çerkezköy",
            "Tekirdağ-Çorlu",
            "Tekirdağ-Hayrabolu",
            "Tekirdağ-Malkara",
            "Tekirdağ-Muratlı",
            "Tekirdağ-Saray / Tekirdağ",
            "Tekirdağ-Şarköy",
            "Tekirdağ-Tekirdağ Merkez",
            "Tekirdağ-Marmaraereğlisi",
            "Tekirdağ-Ergene",
            "Tekirdağ-Kapaklı",
            "Tekirdağ-Süleymanpaşa",
            "Tokat-Almus",
            "Tokat-Artova",
            "Tokat-Erbaa",
            "Tokat-Niksar",
            "Tokat-Reşadiye",
            "Tokat-Tokat Merkez",
            "Tokat-Turhal",
            "Tokat-Zile",
            "Tokat-Pazar / Tokat",
            "Tokat-Yeşilyurt / Tokat",
            "Tokat-Başçiftlik",
            "Tokat-Sulusaray",
            "Trabzon-Akçaabat",
            "Trabzon-Araklı",
            "Trabzon-Arsin",
            "Trabzon-Çaykara",
            "Trabzon-Maçka",
            "Trabzon-Of",
            "Trabzon-Sürmene",
            "Trabzon-Tonya",
            "Trabzon-Trabzon Merkez",
            "Trabzon-Vakfıkebir",
            "Trabzon-Yomra",
            "Trabzon-Beşikdüzü",
            "Trabzon-Şalpazarı",
            "Trabzon-Çarşıbaşı",
            "Trabzon-Dernekpazarı",
            "Trabzon-Düzköy",
            "Trabzon-Hayrat",
            "Trabzon-Köprübaşı / Trabzon",
            "Trabzon-Ortahisar",
            "Tunceli-Çemişgezek",
            "Tunceli-Hozat",
            "Tunceli-Mazgirt",
            "Tunceli-Nazımiye",
            "Tunceli-Ovacık / Tunceli",
            "Tunceli-Pertek",
            "Tunceli-Pülümür",
            "Tunceli-Tunceli Merkez",
            "Şanlıurfa-Akçakale",
            "Şanlıurfa-Birecik",
            "Şanlıurfa-Bozova",
            "Şanlıurfa-Ceylanpınar",
            "Şanlıurfa-Halfeti",
            "Şanlıurfa-Hilvan",
            "Şanlıurfa-Siverek",
            "Şanlıurfa-Suruç",
            "Şanlıurfa-Şanlıurfa Merkez",
            "Şanlıurfa-Viranşehir",
            "Şanlıurfa-Harran",
            "Şanlıurfa-Eyyübiye",
            "Şanlıurfa-Haliliye",
            "Şanlıurfa-Karaköprü",
            "Uşak-Banaz",
            "Uşak-Eşme",
            "Uşak-Karahallı",
            "Uşak-Sivaslı",
            "Uşak-Ulubey / Uşak",
            "Uşak-Uşak Merkez",
            "Van-Başkale",
            "Van-Çatak",
            "Van-Erciş",
            "Van-Gevaş",
            "Van-Gürpınar",
            "Van-Muradiye",
            "Van-Özalp",
            "Van-Van Merkez",
            "Van-Bahçesaray",
            "Van-Çaldıran",
            "Van-Edremit / Van",
            "Van-Saray / Van",
            "Van-İpekyolu",
            "Van-Tuşba",
            "Yozgat-Akdağmadeni",
            "Yozgat-Boğazlıyan",
            "Yozgat-Çayıralan",
            "Yozgat-Çekerek",
            "Yozgat-Sarıkaya",
            "Yozgat-Sorgun",
            "Yozgat-Şefaatli",
            "Yozgat-Yerköy",
            "Yozgat-Yozgat Merkez",
            "Yozgat-Aydıncık / Yozgat",
            "Yozgat-Çandır",
            "Yozgat-Kadışehri",
            "Yozgat-Saraykent",
            "Yozgat-Yenifakılı",
            "Zonguldak-Çaycuma",
            "Zonguldak-Devrek",
            "Zonguldak-Ereğli / Zonguldak",
            "Zonguldak-Zonguldak Merkez",
            "Zonguldak-Alaplı",
            "Zonguldak-Gökçebey",
            "Zonguldak-Kilimli",
            "Zonguldak-Kozlu",
            "Aksaray-Aksaray Merkez",
            "Aksaray-Ortaköy / Aksaray",
            "Aksaray-Ağaçören",
            "Aksaray-Güzelyurt",
            "Aksaray-Sarıyahşi",
            "Aksaray-Eskil",
            "Aksaray-Gülağaç",
            "Aksaray-Sultanhanı",
            "Bayburt-Bayburt Merkez",
            "Bayburt-Aydıntepe",
            "Bayburt-Demirözü",
            "Karaman-Ermenek",
            "Karaman-Karaman Merkez",
            "Karaman-Ayrancı",
            "Karaman-Kazımkarabekir",
            "Karaman-Başyayla",
            "Karaman-Sarıveliler",
            "Kırıkkale-Delice",
            "Kırıkkale-Keskin",
            "Kırıkkale-Kırıkkale Merkez",
            "Kırıkkale-Sulakyurt",
            "Kırıkkale-Bahşili",
            "Kırıkkale-Balışeyh",
            "Kırıkkale-Çelebi",
            "Kırıkkale-Karakeçili",
            "Kırıkkale-Yahşihan",
            "Batman-Batman Merkez",
            "Batman-Beşiri",
            "Batman-Gercüş",
            "Batman-Kozluk",
            "Batman-Sason",
            "Batman-Hasankeyf",
            "Şırnak-Beytüşşebap",
            "Şırnak-Cizre",
            "Şırnak-İdil",
            "Şırnak-Silopi",
            "Şırnak-Şırnak Merkez",
            "Şırnak-Uludere",
            "Şırnak-Güçlükonak",
            "Bartın-Bartın Merkez",
            "Bartın-Kurucaşile",
            "Bartın-Ulus",
            "Bartın-Amasra",
            "Ardahan-Ardahan Merkez",
            "Ardahan-Çıldır",
            "Ardahan-Göle",
            "Ardahan-Hanak",
            "Ardahan-Posof",
            "Ardahan-Damal",
            "Iğdır-Aralık",
            "Iğdır-Iğdır Merkez",
            "Iğdır-Tuzluca",
            "Iğdır-Karakoyunlu",
            "Yalova-Yalova Merkez",
            "Yalova-Altınova",
            "Yalova-Armutlu",
            "Yalova-Çınarcık",
            "Yalova-Çiftlikköy",
            "Yalova-Termal",
            "Karabük-Eflani",
            "Karabük-Eskipazar",
            "Karabük-Karabük Merkez",
            "Karabük-Ovacık / Karabük",
            "Karabük-Safranbolu",
            "Karabük-Yenice / Karabük",
            "Kilis-Kilis Merkez",
            "Kilis-Elbeyli",
            "Kilis-Musabeyli",
            "Kilis-Polateli",
            "Osmaniye-Bahçe",
            "Osmaniye-Kadirli",
            "Osmaniye-Osmaniye Merkez",
            "Osmaniye-Düziçi",
            "Osmaniye-Hasanbeyli",
            "Osmaniye-Sumbas",
            "Osmaniye-Toprakkale",
            "Düzce-Akçakoca",
            "Düzce-Düzce Merkez",
            "Düzce-Yığılca",
            "Düzce-Cumayeri",
            "Düzce-Gölyaka",
            "Düzce-Çilimli",
            "Düzce-Gümüşova",
            "Düzce-Kaynaşlı",
        };
        
    }
}