// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aracyonetim.database;

namespace aracyonetim.database.Migrations
{
    [DbContext(typeof(AracYonetimContext))]
    [Migration("20200117125322_Aracvelookuplisteklendi")]
    partial class Aracvelookuplisteklendi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aracyonetim.entities.Tables.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("EnSonBakimYetkiliServis")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Motor")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Otomatik")
                        .HasColumnType("bit");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("RuhsatSahibiAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<bool>("Ticari")
                        .HasColumnType("bit");

                    b.Property<int>("YakitId")
                        .HasColumnType("int");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Arac");
                });

            modelBuilder.Entity("aracyonetim.entities.Tables.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("aracyonetim.entities.Tables.LookupList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LookupList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "ALFA ROMEO",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "AUDI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "BENTLEY",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "BMW",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "CHERY",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "CHEVROLET",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "CHRYSLER",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "CITROEN",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "DACIA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "DAIHATSU",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "DFM",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "DODGE",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "FERRARI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "FIAT",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "FORD",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "GEELY",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "GREAT WALL",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "HONDA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "HYUNDAI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "IKCO",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "JAGUAR",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "JEEP",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "KARSAN",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "KIA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "LADA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "LAMBORGINI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "LANCIA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "LAND ROVER",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "MAHINDRA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "MASERATI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "MAZDA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "MERCEDES – BENZ",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "MINI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "MITSUBISHI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "NISSAN",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "OPEL",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "OTOKAR",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "PEUGEOT",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "PORSCHE",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "PROTON",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "RENAULT",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "SAAB",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "SEAT",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "SKODA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "SMART",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "SSANGYONG",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "SUBARU",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "SUZUKI",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "TATA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "TOYOTA",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "VOLKSWAGEN",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "VOLVO",
                            Status = (short)0,
                            Tip = 0
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "Dizel",
                            Status = (short)0,
                            Tip = 1
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "Benzin",
                            Status = (short)0,
                            Tip = 1
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "LPG",
                            Status = (short)0,
                            Tip = 1
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 0,
                            IsDeleted = false,
                            Isim = "Elektrik",
                            Status = (short)0,
                            Tip = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
